apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: coi33ej8i-nodejs 
  janus-idp.io/tekton: coi33ej8i-nodejs
  backstage.io/kubernetes-id: coi33ej8i-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: coi33ej8i-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml