apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: coi33ej8i-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: coi33ej8i-nodejs 
  name: coi33ej8i-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: coi33ej8i-nodejs 
